setup-ant: automatically find `android` command

diff --git a/setup-ant b/setup-ant
--- a/setup-ant
+++ b/setup-ant
@@ -1,5 +1,18 @@
 #!/bin/sh
 
+if ! which android > /dev/null; then
+    if [ -z $ANDROID_HOME ]; then
+        if [ -e ~/.android/bashrc ]; then
+            . ~/.android/bashrc
+        else
+            echo "'android' not found, ANDROID_HOME must be set!"
+            exit
+        fi
+    else
+        export PATH="${ANDROID_HOME}/tools:$PATH"
+    fi
+fi
+
 projectname=`sed -n 's,.*name="app_name">\(.*\)<.*,\1,p' res/values/strings.xml`
 
 # fetch target from project.properties
